---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-subns-generator
spec:
  # This is ignored when using the Development runtime.
  package: xpkg.upbound.io/linuxarpan/func-subns-generator:v0.0.8-bug
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.1.4
